//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Manufacture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.Specification = new HashSet<Specification>();
        }
    
        public int Id { get; set; }
        public int ItemId { get; set; }
        public bool IsProduct { get; set; }
        public string Code { get; set; }
        public string productType => IsProduct ? "Да" : "Нет";
        public virtual Material Material { get; set; }
        public virtual ICollection<Specification> Specification { get; set; }
    }
}
