//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Manufacture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Manufacturer = new HashSet<Manufacturer>();
            this.OrderProduct = new HashSet<OrderProduct>();
            this.Specification = new HashSet<Specification>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int UnitId { get; set; }
    
        public virtual ICollection<Manufacturer> Manufacturer { get; set; }
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<Specification> Specification { get; set; }
    }
}
